# Generated by Django 3.2 on 2024-11-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='client',
            new_name='Cliente',
        ),
    ]
